DROP TABLE IF EXISTS RECIPE_DATA;
create table RECIPE_DATA (
	id INT,
	recipe_name VARCHAR(15),
	cuisine_type VARCHAR(8),
	total_cook_time VARCHAR(17)
	
);
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (1, 'Pasta Al Denete', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (2, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (3, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (4, 'Pasta Al Denete', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (5, 'Brisket', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (6, 'Pasta Al Denete', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (7, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (8, 'Smoked Chicken', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (9, 'Smoked Chicken', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (10, 'Brisket', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (11, 'Smoked Chicken', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (12, 'Smoked Chicken', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (13, 'Smoked Chicken', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (14, 'Smoked Chicken', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (15, 'Brisket', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (16, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (17, 'Smoked Chicken', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (18, 'Brisket', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (19, 'Brisket', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (20, 'Pasta Al Denete', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (21, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (22, 'Smoked Chicken', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (23, 'Pasta Al Denete', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (24, 'Pasta Al Denete', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (25, 'Pasta Al Denete', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (26, 'Smoked Chicken', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (27, 'Brisket', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (28, 'Pasta Al Denete', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (29, 'Brisket', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (30, 'Pasta Al Denete', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (31, 'Pasta Al Denete', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (32, 'Pasta Al Denete', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (33, 'Pasta Al Denete', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (34, 'Pasta Al Denete', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (35, 'Brisket', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (36, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (37, 'Pasta Al Denete', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (38, 'Smoked Chicken', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (39, 'Smoked Chicken', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (40, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (41, 'Smoked Chicken', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (42, 'Pasta Al Denete', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (43, 'Pasta Al Denete', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (44, 'Brisket', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (45, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (46, 'Brisket', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (47, 'Pasta Al Denete', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (48, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (49, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (50, 'Pasta Al Denete', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (51, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (52, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (53, 'Smoked Chicken', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (54, 'Smoked Chicken', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (55, 'Smoked Chicken', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (56, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (57, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (58, 'Pasta Al Denete', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (59, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (60, 'Pasta Al Denete', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (61, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (62, 'Smoked Chicken', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (63, 'Pasta Al Denete', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (64, 'Smoked Chicken', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (65, 'Smoked Chicken', 'American', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (66, 'Brisket', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (67, 'Smoked Chicken', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (68, 'Smoked Chicken', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (69, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (70, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (71, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (72, 'Pasta Al Denete', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (73, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (74, 'Pasta Al Denete', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (75, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (76, 'Smoked Chicken', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (77, 'Smoked Chicken', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (78, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (79, 'Brisket', 'Mexican', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (80, 'Smoked Chicken', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (81, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (82, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (83, 'Pasta Al Denete', 'Mexican', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (84, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (85, 'Brisket', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (86, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (87, 'Smoked Chicken', 'Italian', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (88, 'Smoked Chicken', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (89, 'Brisket', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (90, 'Pasta Al Denete', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (91, 'Smoked Chicken', 'American', '30 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (92, 'Pasta Al Denete', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (93, 'Smoked Chicken', 'American', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (94, 'Pasta Al Denete', 'Italian', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (95, 'Pasta Al Denete', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (96, 'Smoked Chicken', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (97, 'Brisket', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (98, 'Pasta Al Denete', 'Italian', '1 hour 15 minutes');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (99, 'Smoked Chicken', 'Mexican', '2 hours');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time) values (100, 'Pasta Al Denete', 'Mexican', '1 hour 15 minutes');
