create table RECIPE_DATA (
	id INT,
	recipe_name VARCHAR(14),
	cuisine_type VARCHAR(8),
	total_cook_time VARCHAR(17),
	recipe_description VARCHAR(25)
);
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (1, 'Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (2, 'Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (3, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (4, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (5, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (6, 'Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (7, 'Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (8, 'Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (9, 'Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (10, 'Smoked Chicken', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (11, 'Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (12, 'Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (13, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (14, 'Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (15, 'Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (16, 'Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (17, 'Brisket', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (18, 'Brisket', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (19, 'Brisket', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (20, 'Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (21, 'Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (22, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (23, 'Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (24, 'Brisket', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (25, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (26, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (27, 'Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (28, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (29, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (30, 'Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (31, 'Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (32, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (33, 'Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (34, 'Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (35, 'Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (36, 'Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (37, 'Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (38, 'Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (39, 'Pasta Al Dente', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (40, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (41, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (42, 'Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (43, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (44, 'Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (45, 'Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (46, 'Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (47, 'Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (48, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (49, 'Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (50, 'Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (51, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (52, 'Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (53, 'Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (54, 'Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (55, 'Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (56, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (57, 'Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (58, 'Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (59, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (60, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (61, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (62, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (63, 'Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (64, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (65, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (66, 'Smoked Chicken', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (67, 'Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (68, 'Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (69, 'Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (70, 'Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (71, 'Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (72, 'Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (73, 'Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (74, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (75, 'Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (76, 'Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (77, 'Brisket', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (78, 'Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (79, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (80, 'Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (81, 'Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (82, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (83, 'Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (84, 'Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (85, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (86, 'Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (87, 'Brisket', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (88, 'Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (89, 'Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (90, 'Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (91, 'Brisket', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (92, 'Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (93, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (94, 'Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (95, 'Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (96, 'Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (97, 'Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (98, 'Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (99, 'Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (id, recipe_name, cuisine_type, total_cook_time, recipe_description) values (100, 'Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
