DROP TABLE IF EXISTS RECIPE_DATA;

create table RECIPE_DATA (
	id INT NOT NULL AUTO_INCREMENT,
	recipe_name VARCHAR(14),
	cuisine_type VARCHAR(8),
	total_cook_time VARCHAR(17),
	recipe_description VARCHAR(25)
);
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Italian', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '1 hour 15 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'American', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Smoked Chicken', 'American', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '2 hours', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Brisket', 'Mexican', '30 minutes', 'Text and description here');
insert into RECIPE_DATA (recipe_name, cuisine_type, total_cook_time, recipe_description) values ('Pasta Al Dente', 'Italian', '1 hour 15 minutes', 'Text and description here');
